### ISSUE TITLE
CraftCMS 4 Support and project status update

### ISSUE THREAD

**Issue by davidhellmann** [doublesecretagency/craft-spoon#117]
Hey,

do you plan to support craft 4 and is there a rough timeline for it?
Thanks!

**Comment by joshangell** [comment]
Hey - the answer is yes - timeline is unclear at the moment as I’m in the process of handing this plugin over to someone who will take good care of it going forward.

I’ve not really managed to maintain it properly over the last few years and my circumstances have now changed to the point that its really time I gave it a new home with someone who will give it the time and energy you folks deserve!

Rest assured the person taking it on is well-known and reliable (far more so than me!) and all existing licenses will transfer over to them in due course.

Please bear with me as we make the transfer and then I’m sure the first thing they will work on will be Craft 4 support.

Thanks!

Josh

**Comment by johnwbaxter** [comment]
Woo!

**Comment by lindseydiloreto** [comment]
Ahoy there! If you're following this thread, you may have already noticed that Spoon has been transferred into the care of Double Secret Agency. While some of the details are still being worked out, you can see that this repo is now tied to our Github organization.

Updating to Craft 4 will be our top priority. You can expect Spoon to be C4 compatible **within the next 1-2 weeks**.

A special thank you to @joshangell for choosing us to be good stewards of his plugin... we will try to make you proud by keeping Spoon updated, and providing the level of support that we are known for. 🙏

**Comment by joshangell** [comment]
🙇‍♂️, exits stage right 👋

**Comment by mortendk** [comment]
awesome :)

**Comment by lindseydiloreto** [comment]
For those following this thread, a quick update...

We are still very actively working on the Craft 4 conversion. In fact, we believed we were about 90% finished when we ran into a snag. Apparently the _field layout designer_ (something Spoon relies heavily on) changed notably in Craft 4. It put us in a tricky position... should we rebuild the FLD in Vue, or hack it further to try and get it working in C4?

So inevitably, we are rebuilding the FLD in Vue. It's been a ton of work migrating away from the native Craft UX, but also a relief to no longer rely on something that could (and did) change unexpectedly.

Optimistically, our goal is to get everything out **within the next 2-3 weeks**. The refactoring has been a big deal, but is progressing well so far. Sorry it's taking longer than expected, but I figured you'd all appreciate a quick status report.

Will keep you posted as we work our way towards the finish line! 🤞

**Comment by bossanova808** [comment]
@lindseydiloreto Any further updates?

**Comment by anbod-io** [comment]
- Over 1300 active installs
- 59 bucks for the first year, and I know I'm not the only one who has paid multiple renewal fees
- Lets be conservative and say the plugin in has pulled a good 100k

I good hunk of money, paid in good faith, and yet well over a 1000 sites in production are not permitted to update to Craft v4.
Can't really call that thing to be proud of, can we.

**Comment by lindseydiloreto** [comment]
@bossanova808 Fair question. I’ve made some progress, albeit slowly.

Rebuilding the field layout designer in Vue has been a massive undertaking. It's been a significant learning curve for me, getting my head around the nuances of Vue 3 and Pinia. I even enlisted @michtio to help speed up the process... I’d like to think the worst of it is now behind us.

I’m hoping to have everything all wrapped us within the next few weeks. It’s my personal goal to have this update complete before Dot All... partly because it would be embarrassing to show up with this plugin unfinished.

**Comment by lindseydiloreto** [comment]
@anbod-io It would be nice if you gave me 24 hours to respond to Jeremy before deciding to get all huffy about it.

To be clear, we acquired Spoon _after_ Craft 4 had already been released. If you've been following this thread, you'll notice that Double Secret Agency has only owned this plugin for a few months, and we've spent much of that time trying to get Spoon up to speed for Craft 4.

I respect the fact that you (and many others) have paid for this plugin, but please realize that 97% of those profits have gone to the previous developer. Your "conservative" estimate of 100k significantly overestimates the actual amount this plugin has earned, and again, almost none of it has gone into my pockets. Despite that, I was willing to pay for outside help last week in order to speed up the conversion process.

Converting Spoon to Craft 4 has been a huge deal, as mentioned previously. Because of some underlying changes in Craft itself, I was forced to rewrite a significant portion of the plugin. It's far from ideal, but absolutely necessary to keep the plugin healthy and compatible moving forward.

In the meantime, I've tried to be as honest and transparent as possible. There are more status updates on this thread than on many other plugins which still haven't made the transition to Craft 4.

Trust me, I'm as eager as you are for this conversion to be finished.

**Comment by bossanova808** [comment]
Did not mean to kick up a fuss, and understand your difficulties @lindseydiloreto ...but also trying to find a way forward.  Obviously, given Spoon doesn't touch data, I can just install and carry on, then later re-install.  

Only issue with that is that our content editor would take a giant leap back in terms of niceness-of-use, and that config would be lost (there's no way to save config to reload later is there?  I presume it's lost when one uninstalls...)

**Comment by lindseydiloreto** [comment]
That's a great question @bossanova808, and I'm not sure I know the answer. It looks like Josh had to rig up some custom code for Project Config to get it to play nicely. I'm not certain how stable that was on Craft 3, or how much it's changed in Craft 4.

If possible, I'd recommend holding out hope a little longer. I know I've promised it before, but I should realistically have the plugin done within the next few weeks. I can't bear the thought of going to Dot All without finishing Spoon first.

If Dot All comes and goes, and you still haven't heard from me, feel free to circle back and harass me about Spoon.

**Comment by lindseydiloreto** [comment]
![Farnsworth](https://user-images.githubusercontent.com/5309692/190520252-fc0d5b9f-22b2-498d-a1be-6f2cfe5844bf.png)

It took _a lot_ longer than expected, but I've finally done it... feast your eyes on **a Craft 4 compatible version of Spoon!**

```json
"doublesecretagency/craft-spoon": "^4.0.0-beta",
```

^ Just pop that line into your `composer.json` file (or update the line that's already there) and run `composer update`.

---

### Vue-based Field Layout Designer

For the most part, this was just a direct port to Craft 4. However, there was a significant portion of the plugin which relied on Craft's internal _field layout designer_. This turned out to be problematic, and I was forced to rewrite the entire FLD in Vue.

The new Vue-based FLD is incredibly stable, though may still have a few minor bugs to work out. Please open a new Github thread if you discover any odd behavior.

### Beta Status

You'll notice that the plugin is currently still in beta for Craft 4. You all are the first to see this update, so please let me know if you have any immediate feedback.

Similarly, the plugin has not yet been thoroughly tested with **Super Table**. We'll make certain that Spoon is fully compatible with Super Table before it graduates out of beta.

Thanks everyone, looking forward to your feedback! 🚀

**Comment by lindseydiloreto** [comment]
Quick follow up... **Spoon 4.0 has graduated from beta!**  🍾 

```json
"doublesecretagency/craft-spoon": "^4.0",
```

The plugin is now compatible with Super Table, and seems to be pretty stable on Craft 4. There may still be minor bugs to find, but there's no reason to keep it in beta now that we have Super Table compatibility.

If you discover any bugs, please open a new Github thread. Thanks for your patience everyone! ❤️
